<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <OutputType>Library</OutputType>
    <AssemblyName>ProgressODoom</AssemblyName>
    <RootNamespace>ProgressODoom</RootNamespace>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Icons\*.ico" />
  </ItemGroup>

</Project>
