<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <Version>2.2.6.0</Version>
    <OutputType>WinExe</OutputType>
    <AssemblyName>CUERipper</AssemblyName>
    <RootNamespace>CUERipper</RootNamespace>
    <ApplicationIcon>cue2.ico</ApplicationIcon>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Freedb\Freedb.csproj" Condition="'$(EnableDormantFreedb)' == 'true'" />
    <ProjectReference Include="..\CUEControls\CUEControls.csproj" />
    <ProjectReference Include="..\CUETools.AccurateRip\CUETools.AccurateRip.csproj" />
    <ProjectReference Include="..\CUETools.CDImage\CUETools.CDImage.csproj" />
    <ProjectReference Include="..\CUETools.Codecs\CUETools.Codecs.csproj" />
    <ProjectReference Include="..\CUETools.CTDB.Types\CUETools.CTDB.Types.csproj" />
    <ProjectReference Include="..\CUETools.CTDB\CUETools.CTDB.csproj" />
    <ProjectReference Include="..\CUETools.Processor\CUETools.Processor.csproj" />
    <ProjectReference Include="..\CUETools.Ripper\CUETools.Ripper.csproj" />
    <ProjectReference Include="..\ProgressODoom\ProgressODoom.csproj" />
    <ProjectReference Include="..\ThirdParty\taglib-sharp\src\TaglibSharp\TaglibSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
