<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <AssemblyName>CUERipper.WPF</AssemblyName>
    <RootNamespace>CUERipper.WPF</RootNamespace>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>$(CueToolsBinRoot)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)$(Configuration)\$(TargetFramework)\</IntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CUEControls\CUEControls.csproj" />
    <ProjectReference Include="..\CUETools.CDImage\CUETools.CDImage.csproj" />
    <ProjectReference Include="..\CUETools.Processor\CUETools.Processor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="musicbrainz.ico" />
    <None Remove="freedb16.png" />
    <Resource Include="musicbrainz.ico" />
    <Resource Include="freedb16.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
