<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <OutputType>Library</OutputType>
    <AssemblyName>CUETools.CTDB.EACPlugin</AssemblyName>
    <RootNamespace>CUETools.CTDB.EACPlugin</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
    <OutputPath>..\bin\$(Configuration)\$(TargetFramework)\interop\EAC\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)\$(Configuration)\$(TargetFramework)\</IntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Interop.HelperFunctionsLib">
      <HintPath>.\Interop.HelperFunctionsLib.dll</HintPath>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CUETools.AccurateRip\CUETools.AccurateRip.csproj" />
    <ProjectReference Include="..\CUETools.CDImage\CUETools.CDImage.csproj" />
    <ProjectReference Include="..\CUETools.Codecs\CUETools.Codecs.csproj" />
    <ProjectReference Include="..\CUETools.CTDB.Types\CUETools.CTDB.Types.csproj" />
    <ProjectReference Include="..\CUETools.CTDB\CUETools.CTDB.csproj" />
    <ProjectReference Include="..\CUETools.Parity\CUETools.Parity.csproj" />
  </ItemGroup>

</Project>
