<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1</TargetFrameworks>
    <Version>1.0.0.0</Version>
    <OutputType>Library</OutputType>
    <AssemblyName>CUETools.TestHelpers</AssemblyName>
    <RootNamespace>CUETools.TestHelpers</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>$(CueToolsBinRoot)tests\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)$(Configuration)\$(TargetFramework)\</IntermediateOutputPath>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <ProjectReference>
      <Private>False</Private>
    </ProjectReference>
  </ItemDefinitionGroup>

  <ItemGroup>
    <ProjectReference Include="..\CUETools.AccurateRip\CUETools.AccurateRip.csproj" />
    <ProjectReference Include="..\CUETools.CDImage\CUETools.CDImage.csproj" />
    <ProjectReference Include="..\CUETools.Codecs\CUETools.Codecs.csproj" />
  </ItemGroup>

</Project>
