<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <AssemblyName>CUETools.ChaptersToCue</AssemblyName>
    <RootNamespace>CUETools.ChaptersToCue</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CUETools.CDImage\CUETools.CDImage.csproj" />
    <ProjectReference Include="..\CUETools.CTDB.Types\CUETools.CTDB.Types.csproj" />
    <ProjectReference Include="..\CUETools.CTDB\CUETools.CTDB.csproj" />
    <ProjectReference Include="..\CUETools.Codecs\CUETools.Codecs.csproj" />
    <ProjectReference Include="..\ThirdParty\taglib-sharp\src\TaglibSharp\TaglibSharp.csproj" />
  </ItemGroup>

</Project>
