<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1</TargetFrameworks>
    <AssemblyName>Freedb</AssemblyName>
    <RootNamespace>Freedb</RootNamespace>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

</Project>
