<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <Version>2.2.6.0</Version>
    <OutputType>Exe</OutputType>
    <AssemblyName>CUETools.FLACCL.cmd</AssemblyName>
    <RootNamespace>CUETools.FLACCL.cmd</RootNamespace>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>$(CueToolsBinRoot)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)$(Configuration)\$(TargetFramework)\</IntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CUETools.Codecs.Flake\CUETools.Codecs.Flake.csproj" />
    <ProjectReference Include="..\CUETools.Codecs\CUETools.Codecs.csproj" />
    <ProjectReference Include="..\CUETools.Codecs.FLACCL\CUETools.Codecs.FLACCL.csproj" />
    <ProjectReference Include="..\ThirdParty\openclnet\source\OpenCLNet.csproj" />
  </ItemGroup>

</Project>
